# Generated by Django 2.2.1 on 2020-04-17 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200416_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='country',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='d_rate',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='d_rate_nums',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='good',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='leader',
        ),
        migrations.AlterField(
            model_name='movie',
            name='pic',
            field=models.FileField(max_length=256, upload_to='movie_cover', verbose_name='封面图片'),
        ),
    ]
