# Generated by Django 2.2.1 on 2020-04-17 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200417_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='电影名称'),
        ),
    ]
